# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

env:
  global:
    - WORKSPACE=Example/BoxCat.xcworkspace
    - DESTINATION="OS=10.0,name=iPhone SE" 
    - SCHEME=BoxCat_Tests 
    - SDK="iphonesimulator10.0" 
    - COVERAGE=YES

podfile: Podfile

osx_image: xcode8

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
before_script:
  - pod lib lint --quick
  - xcodebuild -version
after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^BoxCat$' -cF ios  
script:
  - xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -enableCodeCoverage $COVERAGE test

