# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

env:
  global:
    - WORKSPACE=Example/BoxCat.xcworkspace
    - COVERAGE=NO

podfile: Podfile

osx_image: xcode8

matrix:
  include:
    - env: DESTINATION="OS=10.0,name=iPhone SE" SCHEME=BoxCat_Tests SDK="iphonesimulator10.0" COVERAGE=YES
  before_install:
    - gem install cocoapods # Since Travis is not always on latest version
    - pod install --project-directory=Example
  before_script:
    - pod lib lint --quick
    - xcodebuild -version
  after_success:
    - bash <(curl -s https://codecov.io/bash) -J '^BoxCat$' -cF ios  
  script:
    - set -o pipefail
    - xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ENABLE_TESTABILITY=YES -enableCodeCoverage $COVERAGE test | xcpretty;

