# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BoxCat-Example' -cF ios -X gcov
script:
- pod lib lint
- cd Example
- xcodebuild -version
- xcodebuild -workspace BoxCat.xcworkspace -scheme BoxCat_Tests -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO test
