# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
- pod lib lint
- xcodebuild -version
- xcodebuild -workspace Example/BoxCat.xcworkspace -scheme BoxCat_Tests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
- bash <(curl -s https://codecov.io/bash) -J '^BoxCat$' -cF ios
